name: test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test action
        run: echo "Hello World"
        shell: bash

  test-terminate:
    runs-on: ubuntu-latest
    steps:
      - name: terminate test
        run: echo "Good bye World"
        shell: bash

  admin-console-backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        name: Login to Image Registry
        with:
          registry: registry.rapidautomation.ai
          username: ci_rapflow
          password: p2B3^92ubgPQ
      - run: cd admin-console/app-backend
